const config = {
    initial:'initialize',
    states:{
        initialize:{
            invoke:[{
                    id:'connect-to-server',
                    src:'connectToServer'
                },
                {
                    id:'connect-to-database',
                    src:'connectToDatabase'
                }
            ],
            on:{
                CONNECTED:{
                    actions:['assignSocket'],
                    target:'login'
                },
                NOT_CONNECTED:{
                    target:'login'
                }
            }
        },
        login:{
            on:{
                SUBMIT:{
                    actions:['assignUsername'],
                    target:'listening'
                }
            }
        },
        listening:{
            invoke:{
                id:'listening-to-server',
                src:'listeningToServer'
            },
            on:{
                INTRODUCE_USER:{
                    actions:['emitIntroduce']
                },
                ASSIGN_USERNAME:{
                    actions:['assignMessage']
                },
                GET_ALL_USERS:{
                    actions:['requestUsers']
                },
                ASSIGN_USERS:{
                    actions:['assignUsers']
                }
            }
        }
    }
}

export default config;